version: "3.7"

services:
  example:
    container_name: eng-zap-challenge-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "4200:4200"
